"""Initial layer for GNN to construct hidden states."""
import tensorflow as tf


class DenseInitializer(tf.keras.layers.Layer):
    """Initial hidden state generated from a Dense layer for Message Passing Network."""

    def __init__(self, hidden_state_size=10, *args, **kwargs):
        super(DenseInitializer, self).__init__(*args, **kwargs)
        self.hidden_state_size = hidden_state_size
        # Init inner layers
        self.init = tf.keras.layers.Dense(units=hidden_state_size, name="initializer-dense")

    def call(self, node_features, training=None):
        batch_size = tf.shape(node_features)[0]
        num_nodes = tf.shape(node_features)[1]
        num_dims = tf.shape(node_features)[2]
        nodes = tf.reshape(node_features, [batch_size*num_nodes, num_dims])
        # Init hidden states
        hidden = self.init(nodes, training=training)
        # Restore batches
        return tf.reshape(hidden, [batch_size, num_nodes, self.hidden_state_size])

class PadInitializer(tf.keras.layers.Layer):
    """Initial hidden state generated by padding for Message Passing Network.

    This inititalizer layer takes the node features and pads them with the given pad_value, which
    defaults to 0, until hidden_state_size reached.
    """

    def __init__(self, hidden_state_size=10, pad_value=0, *args, **kwargs):
        super(PadInitializer, self).__init__(*args, **kwargs)
        self.hidden_state_size = hidden_state_size
        self.pad_value = pad_value
        # Init inner layers
        self.init = tf.keras.layers.Dense(units=hidden_state_size, name="initializer-dense")

    def call(self, node_features, training=None):
        batch_size = tf.shape(node_features)[0]
        num_nodes = tf.shape(node_features)[1]
        num_dims = tf.shape(node_features)[2]
        nodes = tf.reshape(node_features, [batch_size*num_nodes, num_dims])
        # Init hidden states
        hidden = self.init(nodes, training=training)
        # Restore batches
        return tf.reshape(hidden, [batch_size, num_nodes, self.hidden_state_size])
