output_path: ./logs
train_dataset: ./data/train
validation_dataset: ./data/validation

# OPTIMIZATION OPTIONS
loss: MeanSquaredError
optimizer:
  type: Adam
  learning_rate:
    type: PolynomialDecay
    decay_steps: 20000
    end_learning_rate: 1.84e-5
    initial_learning_rate: 1.84e-4
    power: 1.0
metrics: [MeanAbsoluteError]

# TRAINING OPTIONS
batch_size: 1
epochs: 20
epoch_size: 10000
shuffle_training_set: False
shuffle_validation_set: False
val_samples: 1000
val_frequency: 1
